# 규칙에 포함할 파일들
included:
    - ${PROJECT_DIR}/RecommendLoLChams-Flab/Sources

# 실행에서 제외할 디폴트규칙
disabled_rules:
    - trailing_whitespace # 행 끝의 공백
    - blanket_disable_command
    
# 선택적으로 적용할 규칙
opt_in_rules:
    - empty_count # isEmpty 사용
    - explicit_init # 구조체, 클래스의 initialize를 명시적으로 선언 .init() 불가능
    - closure_end_indentation # 클로저의 종료 괄호는 클로저를 시작한는 줄과 동일한 수준으로 들여쓰기
    - sorted_imports # import 정렬
    - force_unwrapping
    - array_init
    - closure_spacing
    - collection_alignment
    - colon
    - convenience_type
    - discouraged_object_literal
    - empty_collection_literal
    - empty_string
    - enum_case_associated_values_count
    - fatal_error_message
    - first_where
    - implicitly_unwrapped_optional
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - redundant_nil_coalescing
    - redundant_type_annotation
    - strict_fileprivate
    - toggle_bool
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - vertical_whitespace_closing_braces
    - yoda_condition

# 함수의 복잡성(조건문, 반복문 등의 중첩)를 제한합니다
cyclomatic_complexity:
    warning: 6      # 복잡도가 6를 초과할 경우 경고
    error: 10       # 복잡도가 10를 초과할 경우 에러
