# 실행에서 제외할 디폴트규칙
disabled_rules:
    - trailing_whitespace # 행 끝의 공백
    - blanket_disable_command
    
# 선택적으로 적용할 규칙
opt_in_rules:
    - empty_count # isEmpty 사용
    - explicit_init # 구조체, 클래스의 initialize를 명시적으로 선언 .init() 불가능
    - closure_end_indentation # 클로저의 종료 괄호는 클로저를 시작한는 줄과 동일한 수준으로 들여쓰기
    - sorted_imports # import 정렬
    - force_unwrapping

# 함수의 복잡성(조건문, 반복문 등의 중첩)를 제한합니다
cyclomatic_complexity:
    warning: 2    # 복잡도가 2를 초과할 경우 경고
    error: 5      # 복잡도가 5를 초과할 경우 에러

# 규칙에서 제외할 파일들
excluded:
    - Pods
    - RecommendLoLChams-Flab/AppDelegate.swift
    - '**/SourcePackages/**'
